config/routes.rb
Rails.application.routes.draw do
  get 'crowds/new'
  # get 'events/show'
  # get 'events/new'
  # get 'events/create'
  # get 'events/edit'
  # get 'events/update'
  # get 'events/destroy'
  devise_for :users

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  root to: 'pages#home'

  resources :mobfriends do
    resources :jobs, only: :create
    get 'your-events', to: 'pages#your_events', as: 'your_events'
  end

  resources :jobs, only: :destroy


  resources :events do
    resources :crowds, only: [:new, :create]
  end

  resources :crowds, only: [:destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue pt-4 navbar-light navbar-lewagon">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Become Popular</h5>
        <p>Be the talk of the town with Mobfriends. Get your very own professional friend at Mobfriends, our talented individuals can give a speech at your wedding, go on a movie date with you or even promote your business!</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <%= link_to 'Home', root_path %>
          </li>
          <li>
            <%= link_to 'Find Mobfriends', mobfriends_path %>
          </li>
          <li>
            <%= link_to 'My Events', events_path %>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">


      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019
    <a href="https://lewagon.com/"> Built with ❤️ at Le Wagon Singapore</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_cropped.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'See Mobfriends', mobfriends_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Create Event', new_event_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Join Mob', events_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <%= image_tag "koala.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Events", dashboard_path, class: "dropdown-item" %>
            <% if current_user.mobfriend.present? && current_user.mobfriend.persisted? %>
              <%= link_to "My Profile", mobfriend_path(current_user.mobfriend), class: "dropdown-item" %>
            <% else %>
              <%= link_to "Become Mobfriend", new_mobfriend_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "My Messages", "#", class: "dropdown-item" %>
            <%= link_to "My Account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>