config/routes.rb
Rails.application.routes.draw do
  get 'crowds/new'
  # get 'events/show'
  # get 'events/new'
  # get 'events/create'
  # get 'events/edit'
  # get 'events/update'
  # get 'events/destroy'
  devise_for :users

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  root to: 'pages#home'

  resources :mobfriends do
    resources :jobs, only: :create
    get 'your-events', to: 'pages#your_events', as: 'your_events'
  end

  resources :jobs, only: :destroy


  resources :events do
    resources :crowds, only: [:new, :create]
  end

  resources :crowds, only: [:destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mobfriend.rb
class Mobfriend < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :user
  has_many :jobs, dependent: :destroy
  has_many :events, through: :jobs

  validates :tagline, presence: true, length: { maximum: 140 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true, length: { maximum: 600 }
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 18, less_than: 100 }
  validates :gender, presence: true, inclusion: { in: %w[male female] }
  validates :language, presence: true
  validates :hourly_rate, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 25 }
end

app/controllers/mobfriends_controller.rb
class MobfriendsController < ApplicationController
  before_action :set_mobfriends, only: [:index]
  before_action :set_mobfriend, only: [:show, :edit, :update, :destroy]

  # CREATE: new (form) & create
  def new
    @mobfriend = Mobfriend.new
    authorize @mobfriend
  end

  def create
    @mobfriend = Mobfriend.new(mobfriend_new_params)
    authorize @mobfriend
    @mobfriend.user = current_user
    if @mobfriend.save
      redirect_to mobfriend_path(@mobfriend)
    else
      render 'new'
    end
  end

  # READ: index & show
  def index
    @mobfriends = policy_scope(Mobfriend).order(created_at: :desc)
    @adjective_arr = %w[young old slim fat tall chinese asian african european happy sad angry gangster]
    @job = Job.new
  end

  def show
    authorize @mobfriend
    @job = Job.new
  end

  # UPDATE: edit (form) & update
  def edit
    authorize @mobfriend
  end

  def update
    authorize @mobfriend
    if @mobfriend.update(mobfriend_edit_params)
      redirect_to mobfriend_path(@mobfriend)
    else
      render 'edit'
    end
  end

  # DELETE: destroy
  def destroy
    authorize @mobfriend
    @mobfriend.destroy
    # redirect_to dashboard_path(current_user)
  end

  private

  def set_mobfriends
    @mobfriends = Mobfriend.all
  end

  def set_mobfriend
    @mobfriend = Mobfriend.find(params[:id])
  end

  def mobfriend_new_params
    params.require(:mobfriend).permit(:first_name, :last_name, :hourly_rate, :tagline, :age, :gender, :language, :photo, :bio)
  end

  def mobfriend_edit_params
    params.require(:mobfriend).permit(:tagline, :hourly_rate, :language, :photo_url, :bio)
  end
end

app/views/mobfriends/edit.html.erb
<div class="page-header">
  <h1>Edit Profile</h1>
</div>
<div class="form mobfriend-form">
  <%= simple_form_for @mobfriend do |f|%>
  <% if @mobfriend.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @mobfriend.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <%= f.input :tagline %>
  <%= f.input :hourly_rate %>
  <%= f.input :language %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :bio %>
  <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/mobfriends/index.html.erb
<h1 class='text-center my-5'>Select a Mobfriend</h1>
<div class="mobfriends-container container">
  <div class="row">
    <% @mobfriends.each do |mobfriend| %>
    <div class="col-md-6 col-lg-4">
      <div class="mobfriend-card text-center bg-light shadow-sm my-3 pb-3">
        <div class="mobfriend-card-image-container">
          <%= link_to mobfriend_path(mobfriend) do %>
            <% if mobfriend.photo.url.nil? %>
              <%= image_tag("https://source.unsplash.com/600x400/?sig=#{rand(1..100)}/&#{mobfriend.gender},#{@adjective_arr.sample},face", width: '100%') %>
            <% else %>
              <img src=<%= cl_image_path mobfriend.photo, crop: :fill %> alt=<%= mobfriend.user.username %> style="width: 100%">
            <% end %>
          <% end %>
        </div>
        <div class="mobfriend-details">
          <p><%= "#{mobfriend.first_name} #{mobfriend.last_name}" %></p>
          <p>$<%= mobfriend.hourly_rate %>/hr</p>
        </div>
        <div class="mobfriend-card-tagline">
          <p>
            "<% if mobfriend.tagline.length > 65 %>
            <%= mobfriend.tagline[0..65] %>...
            <% else %>
            <%= mobfriend.tagline %>
            <% end %>"
          </p>
        </div>
        <div class="mobfriend-buttons">
          <div class="btn btn-info">
            <%= link_to 'View', mobfriend_path(mobfriend) %>
          </div>
          <%= link_to 'Add to Booking', mobfriend_your_events_path(mobfriend), class: 'btn btn-info' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/mobfriends/new.html.erb
<div class="page-header">
  <h1>Create Profile</h1>
</div>
<div class="form mobfriend-form">
  <%= simple_form_for @mobfriend do |f|%>
  <% if @mobfriend.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @mobfriend.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :tagline %>
  <%= f.input :hourly_rate %>
  <%= f.input :age %>
  <%= f.input :gender %>
  <%= f.input :language %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :bio %>
  <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/mobfriends/show.html.erb
<div class="header text-center my-5">
  <h1><%= @mobfriend.first_name.capitalize %> <%= @mobfriend.last_name.capitalize %></h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <%= link_to mobfriend_path(@mobfriend) do %>
        <% if @mobfriend.photo.url.nil? %>
          <%= image_tag("https://source.unsplash.com/600x400/?#{@mobfriend.gender},face", width: '100%') %>
        <% else %>
          <img src=<%= cl_image_path @mobfriend.photo, crop: :fill %> alt=<%= @mobfriend.user.username %> style="width: 100%">
        <% end %>
      <% end %>
      <p><em>"<%= @mobfriend.tagline %>"</em></p>
    </div>
    <div class="col-lg-8">
      <p><strong>Asking Rate: </strong><%= @mobfriend.hourly_rate %>/hour</p>
      <p><strong>Age: </strong><%= @mobfriend.age %></p>
      <p><strong>Gender: </strong><%= @mobfriend.gender %></p>
      <p><strong>Language: </strong><%= @mobfriend.language.capitalize %></p>
      <p><strong>Bio: </strong><%= @mobfriend.bio %></p>
    </div>
  </div>
<div class="buttons-container">
  <%= link_to 'View all Mobfriends', mobfriends_path, class: 'btn btn-info' %>
  <% if @mobfriend.user == current_user %>
    <%= link_to 'My Dashboard', dashboard_path, class: 'btn btn-info' %>
    <%= link_to 'Edit Profile', edit_mobfriend_path(@mobfriend), class: 'btn btn-info' %>
  <% end %>
  <% if @mobfriend.user != current_user %>
    <%= link_to 'Add to booking', mobfriend_your_events_path(@mobfriend), class: 'btn btn-info' %>
  <% end %>
</div>
</div>