config/routes.rb
Rails.application.routes.draw do
  get 'crowds/new'
  # get 'events/show'
  # get 'events/new'
  # get 'events/create'
  # get 'events/edit'
  # get 'events/update'
  # get 'events/destroy'
  devise_for :users

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  root to: 'pages#home'

  resources :mobfriends do
    resources :jobs, only: :create
    get 'your-events', to: 'pages#your_events', as: 'your_events'
  end

  resources :jobs, only: :destroy


  resources :events do
    resources :crowds, only: [:new, :create]
  end

  resources :crowds, only: [:destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_one :crowd, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :mobfriends, through: :jobs
  geocoded_by :event_location
  after_validation :geocode, if: :will_save_change_to_event_location?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_events, only: [:index]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = policy_scope(Event).order(created_at: :desc)
    if current_user.mobfriend.present?
      @mobfriend = current_user.mobfriend
      @job = Job.new
    end
    @events = Event.geocoded #returns flats with coordinates
    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude
      }
    end
  end

  def show
    authorize @event
    @date = format_datetime(@event.datetime)
    @total_cost = total_jobs_cost(@event.jobs)
  end

  # form only
  def new
    @event = Event.new
    authorize @event
    @categories = ["wedding", "birthday", "social"]
  end

  # create is the action involved in creation
  def create
    # pass strong params into Event.new
    @event = Event.new(event_params)
    authorize @event
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def edit
    @categories = ["wedding", "birthday", "social"]
    # get event type
    @type = @event.event_type
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to event_path
    else
      render 'edit'
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to dashboard_path
  end

  private

  # add strong event params
  def event_params
    params.require(:event).permit(:datetime, :event_type, :description, :event_location, :meeting_location, :confirmed, :public)
  end

  def set_events
    @events = Event.all
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def format_datetime(datetime)
    hour = datetime.hour
    min = datetime.min
    date = datetime.to_date
    suffix = 'AM'
    if hour > 12
      hour -= 12
      suffix = 'PM'
    end
    "#{date}, #{hour}:#{min} #{suffix}"
  end

  def total_jobs_cost(jobs)
    total_cost = 0
    jobs.each do |job|
      total_cost += job.mobfriend.hourly_rate
    end
    return total_cost
  end
end

app/views/events/_add_crowd_big_btn.html.erb
<div class="card shadow-sm p-5, m-5 d-flex text-center bg-light">
  <p class="p-5"><%= link_to 'Enlist Crowd', new_event_crowd_path(@event) %></p>
</div>

app/views/events/_add_mobfriends_big_btn.html.erb
<div class="card shadow-sm p-5, m-5 d-flex text-center bg-light">
  <p class="p-5"><%= link_to 'Find Mobfriends', mobfriends_path %></p>
</div>

app/views/events/_form.html.erb
<div class="container">
  <%= simple_form_for [@event] do |e| %>
    <%= e.input :datetime %>
    <!-- 'event[category]' formats the data into a key value pair (eg. Hash) -->
    <!-- 'form-control' is a bootstrap class to beautify the dropdown -->
    <select name="event[event_type]" class="form-control" id="">
      <% @categories.each do |c| %>
        <option value="<%= c %>" <%= 'selected' if @type == c %>> <%= c %></option>
      <% end %>
    </select>
    <%= e.input :description %>
    <%= e.input :event_location %>
    <%= e.input :meeting_location %>
    <% if @event.id.present? %>
      <%= e.input :confirmed %>
    <% end %>
    <%= e.input :public, label: 'Public (list event to rent a crowd)' %>
    <%= e.submit "Create", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/events/_list_event_mobfriends.html.erb
<div class="mobfriends-avatar-container container">
  <div class="row">
    <% @event.jobs.each do |job| %>
      <div class="mobfriend-card text-center bg-light rounded shadow-sm my-3 pb-3 col-md-6 col-lg-4">
        <div class="mobfriend-card-image-container">
          <%= link_to mobfriend_path(job.mobfriend) do %>
            <% if job.mobfriend.photo.url.nil? %>
              <%= image_tag("https://source.unsplash.com/600x400/?sig=#{rand(1..100)}/&#{job.mobfriend.gender},face", width: '100%') %>
            <% else %>
              <img src=<%= cl_image_path job.mobfriend.photo, crop: :fill %> alt=<%= job.mobfriend.user.username %> style="width: 100%">
            <% end %>
          <% end %>
        </div>
        <p><%= job.mobfriend.first_name %></p>
        <div class="mobfriend-buttons">
          <div class="btn btn-info"><%= link_to 'View', mobfriend_path(job.mobfriend) %></div>
          <div class="btn btn-danger"><%= link_to 'Delete', job_path(job), method: :delete %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<div class="header">
  <h1>Edit event</h1>
</div>
<%= render 'form' %>

app/views/events/index.html.erb
<div class="header">
  <h1>Event Index</h1>
</div>
<div class="container_events_mapbox">
  <div class="container">
    <div class="row d-flex">
      <div class="events-container col-lg-6">
        <% @events.each do |event| %>
          <ul class="card">
          <li>Event ID: <%= event.id  %></li>
          <li>Event Description: <%= link_to event.description, event_path(event) %></li>
          <li>Location: <%= event.event_location %></li>
          <li><%= event.datetime %></li>
          </ul>
          <% if current_user.mobfriend.present? && event.crowd.present? %>
            <%= simple_form_for [@mobfriend, @job] do |f| %>
            <%= f.hidden_field :event, value: event.id %>
            <%= f.button :submit, value: 'Join Crowd', class: 'btn btn-primary' %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="container_mapbox col-lg-6">
        <div id="map"
          style="width: 100%;
          height: 600px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="header">
  <h1>Create a new event</h1>
</div>
<%= render 'form' %>

app/views/events/show.html.erb
<div class="header">
  <h1>Current Booking</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <%= image_tag("https://source.unsplash.com/600x400/?#{@event.event_type}", width: '100%') %>
    </div>
    <div class="col-lg-8 my-5">
      <ul>
        <li>Description: <%= @event.description %></li>
        <li>Type: <%= @event.event_type %></li>
        <li>Time: <%= @date %></li>
        <li>Location: <%= @event.event_location %></li>
        <li>Total cost: $<%= @total_cost %>/hr</li>
        <% if @event.confirmed %>
          <li>Status: Confirmed</li>
        <% else %>
          <li>Status: Unconfirmed</li>
          <%= simple_form_for @event do |f| %>
          <%= f.hidden_field :confirmed, value: true %>
          <%= f.button :submit, value: 'Confirm', class: 'btn btn-primary my-5' %>
          <% end %>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="row d-flex justify-content-center my-5">
    <%= link_to('All Events', events_path, class: 'btn btn-light mx-3') %>
    <% if policy(@event).update? %>
      <%= link_to('Edit Event', edit_event_path, class: 'btn btn-light mx-3') %>
    <% end %>
    <% if policy(@event).destroy? %>
      <%= link_to('Delete Event', @event, method: :delete, class: 'btn btn-light mx-3') %>
    <% end %>
  </div>
  <h2>Your Mobfriends</h2>
  <% if @event.jobs.present? %>
    <h3>who will be meeting you at
      <em><%= @event.meeting_location %></em>
    </h3>
    <div class="row">
      <%= render 'list_event_mobfriends' %>
    </div>
  <% else %>
    <p>No Mobfriends added to booking...</p>
    <% if @event.public && @event.crowd.present? %>
      <p>Please wait for Mobfriends to join your Crowd</p>
    <% elsif @event.public && @event.crowd.nil? %>
      <%= render 'add_crowd_big_btn' %>
    <% else %>
      <%= render 'add_mobfriends_big_btn' %>
    <% end %>
  <% end %>
</div>