config/routes.rb
Rails.application.routes.draw do
  get 'crowds/new'
  # get 'events/show'
  # get 'events/new'
  # get 'events/create'
  # get 'events/edit'
  # get 'events/update'
  # get 'events/destroy'
  devise_for :users

  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  root to: 'pages#home'

  resources :mobfriends do
    resources :jobs, only: :create
    get 'your-events', to: 'pages#your_events', as: 'your_events'
  end

  resources :jobs, only: :destroy


  resources :events do
    resources :crowds, only: [:new, :create]
  end

  resources :crowds, only: [:destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_dashboard_add_jobs.html.erb
<div class="section">
  <div class="subheader">
    <p>You're a Mobfriend without any gigs</p>
  </div>
  <h3>Join a crowd!</h3>
</div>

app/views/pages/_dashboard_become_mobfriend.html.erb
<div class="section d-flex flex-column justify-content-center mx-auto">
  <div class="message-to-user">
    <p>You're not a Mobfriend</p>
    <div class="card shadow-sm d-flex text-center bg-light">
      <p class="p-5"><%= link_to 'Create Mobfriend profile', new_mobfriend_path %></p>
    </div>
  </div>
</div>

app/views/pages/_dashboard_buttons_bar.html.erb
<div class="buttons-bar d-flex justify-content-center my-3">
  <%= link_to 'Create Event', new_event_path, class: 'btn btn-light' %>
  <%= link_to 'Mobfriend Profile', new_mobfriend_path, class: 'btn btn-light' %>
  <%= link_to 'Join a Gig', events_path, class: 'btn btn-light' %>
</div>

app/views/pages/_dashboard_confirmed_events.html.erb
<% @confirmed_events.each do |event| %>
  <div class="col-lg-4">
    <div class="details-container">
      <%= image_tag("https://source.unsplash.com/600x400/?sig=#{rand(1..100)}/&#{event.event_type}", width: '100%') %>
      <p><strong><%= event.event_type.capitalize %></strong> at
        <%= event.event_location %>,
        <%= "#{event.datetime.hour}:#{event.datetime.min}" %>hrs</p>
    </div>
    <div class="buttons-container">
      <div class="btn btn-success disabled">Confirmed</div>
      <%= link_to('View', event_path(event), class: 'btn btn-light') %>
      <%= link_to('Delete Event', event, method: :delete, class: 'btn btn-light') %>
    </div>
  </div>
<% end %>

app/views/pages/_dashboard_create_event.html.erb
<div class="section d-flex flex-column justify-content-center mx-auto">
  <div class="message-to-user">
    <p>You've no Events at the moment</p>
    <div class="card shadow-sm d-flex text-center bg-light">
      <p class="p-5"><%= link_to 'Create Event', new_event_path %></p>
    </div>
  </div>
</div>

app/views/pages/_dashboard_pending_events.html.erb
<% @pending_events.each do |event| %>
  <div class="col-lg-4">
    <div class="details-container">
      <%= image_tag("https://source.unsplash.com/600x400/?sig=#{rand(1..100)}/&#{event.event_type}", width: '100%') %>
      <p><strong><%= event.event_type.capitalize %></strong> at
        <%= event.event_location %>,
        <%= "#{event.datetime.hour}:#{event.datetime.min}" %>hrs</p>
    </div>
    <div class="buttons-container">
      <%= simple_form_for event do |f| %>
      <%= f.hidden_field :confirmed, value: true %>
      <%= f.button :submit, value: 'Confirm', class: 'btn btn-primary' %>
      <% end %>
      <%= link_to('View', event_path(event), class: 'btn btn-light') %>
      <%= link_to('Delete Event', event, method: :delete, class: 'btn btn-light') %>
    </div>
  </div>
<% end %>

app/views/pages/_dashboard_pending_jobs.html.erb
<% @jobs.each.each do |job| %>
  <div class="col-lg-4">
    <div class="details-container">
      <%= image_tag("https://source.unsplash.com/600x400/?sig=#{rand(1..100)}/&#{job.mobfriend.gender},face", width: '100%') %>
      <p><strong><%= job.event.event_type %></strong> at
        <%= job.event.event_location %>,
        <%= "#{job.event.datetime.hour}:#{job.event.datetime.min}" %>hrs</p>
    </div>
    <div class="buttons-container">
      <% if job.accepted %>
        <%= simple_form_for job do |f| %>
          <%= f.hidden_field :accepted, value: true %>
          <%= f.button :submit, value: 'Accept', class: 'btn btn-primary' %>
        <% end %>
      <% else %>
        <div class="btn btn-success disabled">Confirmed</div>
      <% end %>
      <%= link_to('View', event_path(job.event), class: 'btn btn-light') %>
    </div>
  </div>
<% end %>

app/views/pages/dashboard.html.erb
<div class="header">
  <h1><%= current_user.username %>'s dashboard</h1>
</div>
<div class="section" id="events-section">
  <div class="subheader">
    <p>Your events</p>
  </div>
  <div class="container">
    <div class="row d-flex">
      <% if @events.present? %>
        <%= render 'dashboard_pending_events' %>
        <%= render 'dashboard_confirmed_events' %>
      <% else %>
        <%= render 'dashboard_create_event' %>
      <% end %>
    </div>
  </div>
</div>
<div class="section" id="jobs-section">
  <div class="subheader">
    <p>Your gigs</p>
  </div>
  <div class="container">
    <div class="row d-flex">
      <% if @mobfriend.present? %>
        <% if @jobs.present? %>
          <%= render 'dashboard_pending_jobs' %>
        <% else %>
          <%= render 'dashboard_add_jobs' %>
        <% end %>
      <% else %>
        <%= render 'dashboard_become_mobfriend' %>
      <% end %>
    </div>
  </div>

  <% if @events.nil? && @mobfriend.nil?%>
    <%= render 'dashboard_create_event_or_job' %>
  <% end %>
</div>
<%= render 'dashboard_buttons_bar' %>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-fluid mb-0">
<div class="display: flex">
  <div class="landing-page-callout ml-5">
    <h1 class="display-3">Want some friends?</h1>
    <h5 class="ml-3">Rent one today! Starts from $7/hour.</h5>
    <%= link_to 'Sign Up', new_user_registration_path, :class => "btn btn-light ml-3"%>
  </div>
</div>
</div>
<%= render 'shared/footer' %>

app/views/pages/your_events.html.erb
<div class="header">
  <h1>Add Mobfriend to Your Event</h1>
  <div class="container">
    <div class="row">
      <% @pending_events.each do |event| %>
        <div class="col-lg-4">
          <%= image_tag("https://source.unsplash.com/600x400/?#{event.event_type}", width: '100%') %>
        </div>
        <div class="col-lg-8 my-5">
          <ul>
            <li>Type: <%= event.event_type %></li>
            <li>Time: <%= "#{event.datetime.hour}:#{event.datetime.min}" %></li>
            <li>Location: <%= event.event_location %></li>
          </ul>
          <%= simple_form_for [@mobfriend, @job] do |f| %>
          <%= f.hidden_field :event, value: event.id %>
          <%= f.button :submit, value: 'Add to booking', class: 'btn btn-primary' %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>